services:
  # Веб-сервис, объединяющий фронтенд и бэкенд
  - type: web
    name: threatdetector
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile # Укажем путь к Dockerfile
    envVars:
      - key: DOCKER_ENV
        value: true
      - key: BACKEND_CORS_ORIGINS
        value: '["https://threatdetector.onrender.com", "https://*.render.com"]'
    healthCheckPath: /
