services:
  # Веб-сервис, объединяющий фронтенд и бэкенд
  - type: web
    name: threatdetector
    env: docker
    plan: free
    # Указываем порт для приложения
    envVars:
      - key: PORT
        value: 10000
