services:
  # Веб-сервис, объединяющий фронтенд и бэкенд
  - type: web
    name: threatdetector
    env: docker
    plan: free
    # Настройки для автоматического деплоя из GitHub
    buildCommand: docker build -t threatdetector .
    startCommand: docker run -p $PORT:80 threatdetector
    envVars:
      - key: DOCKER_ENV
        value: true
      - key: BACKEND_CORS_ORIGINS
        value: '["https://threatdetector.onrender.com", "https://*.render.com"]'
    healthCheckPath: /
